version: '3.9'

services:
  web:
    build: .
    container_name: stock_web
    command: gunicorn finance_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: stock_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: stock_redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_MAXMEMORY=100mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru

  celery:
    build: .
    container_name: stock_celery
    command: celery -A finance_app worker --loglevel=info --concurrency=1 --prefetch-multiplier=1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: "true"
      C_FORCE_ROOT: "1"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  celery-beat:
    build: .
    container_name: stock_celery_beat
    command: celery -A finance_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
