version: '3.9'

services:
  web:
    build: .
    container_name: stock_web
    command: gunicorn finance_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: stock_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: stock_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: stock_celery
    command: celery -A finance_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web


volumes:
  postgres_data:
