version: '3.9'

services:
  web:
    build: .
    container_name: stock_web
    command: gunicorn finance_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: stock_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: stock_redis
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    environment:
      - REDIS_TIMEOUT=30
      - REDIS_TCP_KEEPALIVE=300
      - REDIS_LOGLEVEL=warning

  celery:
    build: .
    container_name: stock_celery
    command: celery -A finance_app worker --loglevel=info --concurrency=2 --prefetch-multiplier=1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_BROKER_TRANSPORT_OPTIONS: "{'socket_timeout': 30, 'retry_on_timeout': True}"
      C_FORCE_ROOT: "1"  # Remove this if not running as root

  celery-beat:
    build: .
    container_name: stock_celery_beat
    command: celery -A finance_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
